/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/*
 Name        : Led Project
 Author      : Fady Emad
 Version     : 1
 Copyright   : Your copyright notice
 Description : Hello World in C, Ansi-style
 ============================================================================
 */

#include <stdio.h>
#include <stdint.h>
typedef volatile unsigned int vuint32_t;

// register address
//RCC
#define RCC_BASE       0x40021000
#define RCC_APB2ENR   *(vuint32_t *)(RCC_BASE+0x18)
#define RCC_IOPAEN    (1<<2)

//GPIO
#define GPIOA_BASE     0x40010800
#define GPIOA_CRH      *(vuint32_t *)(GPIOA_BASE+0x04)
#define GPIOA_ODR      *(vuint32_t *)(GPIOA_BASE+0x0C)
#define GPIOA13        (1UL<<13)
#define GPIOx_CRL	   *(vuint32_t *)(GPIOA_BASE+0x00)

//EXTI
#define EXTI_BASE     0x40010400
#define EXTI_IMR      *(vuint32_t *)(EXTI_BASE + 0x00)
#define EXTI_RTSR	  *(vuint32_t *)(EXTI_BASE + 0x08)
#define EXTI_PR       *(vuint32_t *)(EXTI_BASE + 0x14)

//AFIO
#define AFIO_BASE     0x40010000
#define AFIO_EXTICR1  *(vuint32_t *)(AFIO_BASE + 0x08)

#define NVIC_EXTI0E  *(vuint32_t *)(0xE000E100)

void clock_init(){
	// enable clock for gpio port a
	RCC_APB2ENR  |=RCC_IOPAEN;

	//enable clock for AFIO
	/*Bit 0  AFIOEN: Alternate function I/O clock enable Set and cleared by software.
	0: Alternate Function I/O clock disabled
	1:Alternate Function I/O clock enabled*/
	RCC_APB2ENR |= (1<<0);


}

void GPIO_init(){
	// SET PIN 13 PORT A IN OUTPUT DIRECTION
	GPIOA_CRH    &=0xFF0FFFFF;
	GPIOA_CRH    |=0x00200000;

	//setting GPIO PORTA0 to input
	//CNF bit 3:2 >>>> floating input
	GPIOx_CRL |= (0b01<<2);
	//MODE bit 1:0
	GPIOx_CRL |= (0b00<<0);
}

int main(void) {
	//enable rising trigger status register
	EXTI_RTSR |= (1<<0);

	//EXTI0 configuration PORT A0
	AFIO_EXTICR1 |=(0b0000<<0);
	//enable interrupt mask register fot line 0
	EXTI_IMR |=(1<<0);

	// Enable NVIC IRQ6 <<<>>> EXTI0
	NVIC_EXTI0E |= (1<<6);

	while(1);
}

void EXTI0_IRQHandler(void){
	// IRQ HAS HAPPENED EXTI0 >>> PORTA PIN 0
	// SO TOGGLE LED ON GPIOA
	GPIOA_ODR ^= (1<<13);
	//clear pending register for line 0 by writing 1 on corressponding bit no 1
	EXTI_PR  |= (1<<0);
}
