/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


//#define MCU_Act_AS_Master
#define MCU_Act_AS_Slave


#include "STM32F103x6.h"
#include "STM32_F103C6_GPIO_Driver.h"
#include "STM32_F103C6_EXTI_Driver.h"
#include "STM32_F103C6_RCC_Driver.h"
#include "STM32_F103C6_USART_Driver.h"
#include "STM32_F103C6_SPI_Driver.h"
#include "lcd.h"
#include "keypad.h"
#include "seven_seg.h"


void clock_init(){

	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
	//To enable EXTI
	RCC_AFIO_CLK_EN();
}

unsigned char ch;




void SPI_Slave_IRQ_Callback (struct S_IRQ_SRC irq_src)
{	if(irq_src.RXNE){
	ch= 0xf;
	MCAL_SPI_TX_RX(SPI1, &ch, Pollingdisable);
	MCAL_UART_SendData(USART1, &ch, enable);
}
}




int main()
{
	clock_init();
	//	LCD_init();
	//	LCD_WriteString("lcd done!!");
	//	LCD_Clear_Screen();
	UART_Config uartCFG;
	SPI_Config_t SPI1CFG;
	GPIO_PINConfig_t PinCnfg;


	//=======================UART INIT==========================
	//PA9	TX
	//PA10	RX
	//PA11	CTS
	//PA12	RTS
	uartCFG.BaudRate = UART_BaudRate_115200;
	uartCFG.HwFlowCtl = UART_HwFlowCtl_NONE;
	uartCFG.Parity = UART_Parity__NONE;
	uartCFG.Payload_Length = UART_Payload_Length_8B;
	uartCFG.StopBits = UART_StopBits__1;
	uartCFG.USART_Mode = UART_MODE_RX;
	uartCFG.IRQ_Enable = UART_IRQ_Enable_NONE;	//when RXNEIE is set go to irq handler to receive(read data from register)
	uartCFG.P_IRQ_CallBack = NULL ;    // address of function without brackets!!!!!!
	MCAL_UART_Init(USART1,&uartCFG);
	MCAL_UART_GPIO_Set_Pins(USART1);



	//=======================SPI INIT==========================
	//PA4	NSS
	//PA5	SCK
	//PA6	MISO
	//PA7	MOSI


	//Common Configuration between master and slave
	SPI1CFG.CLKPhase 			  =	SPI_Clock_Phase_2EDGE_first_data_capture_edge;
	SPI1CFG.CLKPolarity			  =	SPI_CLKPolarity_HIGH_when_idle;
	SPI1CFG.DataSize 			  =	SPI_DataSize_8BIT;
	SPI1CFG.Frame_Format		  =	SPI_Frame_Format_MSB_transmitted_first;
	//assume pclk2 8MHZ by default (NOT MODIFIED)
	SPI1CFG.SPI_BAUDRATEPRESCALER =	SPI_BAUDRATEPRESCALER_8;
	SPI1CFG.Communication_Mode    =	SPI_DIRECTION_2LINES;

#ifdef MCU_Act_AS_Master
	SPI1CFG.Device_Mode		  = SPI_Device_Mode_MASTER;
	SPI1CFG.IRQ_Enable	      = SPI_IRQ_Enable_NONE;
	SPI1CFG.NSS	              = SPI_NSS_Soft_NSSInternalSoft_Set;		//you are the only master on the bus
	SPI1CFG.P_IRQ_CallBack	  = NULL;
	MCAL_SPI_Init(SPI1, &SPI1CFG);
	MCAL_SPI_GPIO_Set_Pins(SPI1);
#endif

#ifdef MCU_Act_AS_Slave
	SPI1CFG.Device_Mode		  = SPI_Device_Mode_SLAVE;
	SPI1CFG.IRQ_Enable	      = SPI_IRQ_Enable_RXNEIE;
	SPI1CFG.NSS	              = SPI_NSS_Hard_Slave;		//you are the only master on the bus
	SPI1CFG.P_IRQ_CallBack	  = SPI_Slave_IRQ_Callback;
	MCAL_SPI_Init(SPI1, &SPI1CFG);
	MCAL_SPI_GPIO_Set_Pins(SPI1);

	//NSS Pin config
	PinCnfg.GPIO_PinNumber 	  = GPIO_PIN_4;
	PinCnfg.GPIO_MODE		  = GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_Init(GPIOA, &PinCnfg);

#endif


	while(1){

	}
}

