/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "STM32F103x6.h"
#include "STM32_F103C6_GPIO_Driver.h"
#include "STM32_F103C6_EXTI_Driver.h"
#include "lcd.h"
#include "keypad.h"
#include "seven_seg.h"



#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void wait(int x){
	unsigned int i,j;
	for (i=0; i<x;i++){
		for(j=0;j<255;j++);
	}
}


void clock_init(){

	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
	//To enable EXTI
	RCC_AFIO_CLK_EN();
}
uint8_t IRQ_Flag=0;

void EXTI9_Callback(){
	LCD_Clear_Screen();
	IRQ_Flag =1 ;
	LCD_WriteString("IRQ EXTI9 happened _|-");
	wait(100);

}

int main()
{
	clock_init();
	LCD_init();
	LCD_Clear_Screen();
	EXTI_PinConfig_t EXTI_CFG;


//Instead of doing this
/*
 * EXTI_CFG.EXTI_PIN.GPIO_PIN= GPIO_PIN_9;
 * EXTI_CFG.EXTI_PIN.GPIO_Port= GPIOB;
 * EXTI_CFG.EXTI_PIN.EXTI_InputLineNumber= EXTI9;
 * EXTI_CFG.EXTI_PIN.IVT_IRQ_Number= EXTI9_IRQ;
 */

// It is easier to do it like that(line below this comment)
	EXTI_CFG.EXTI_PIN = EXTI9PB9;
	EXTI_CFG.IRQ_EN = EXTI_IRQ_Enable;
	EXTI_CFG.P_IRQ_CallBack = EXTI9_Callback;
	EXTI_CFG.Trigger_Case = EXTI_Trigger_RISING;
	MCAL_EXTI_GPIO_Init(&EXTI_CFG);
	LCD_WriteString("Hello and Welcome to my EXTI Test");
	wait(100);
	LCD_Clear_Screen();
	LCD_WriteString("LCD is Ready !!!");
	wait(100);
	LCD_Clear_Screen();
	while(1){

		if(IRQ_Flag){
			LCD_Clear_Screen();
			IRQ_Flag=0;
		}




	}
	return 0;
}
