/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "STM32F103x6.h"
#include "STM32_F103C6_GPIO_Driver.h"
#include "lcd.h"
#include "keypad.h"
#include "seven_seg.h"



#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void wait(int x){
	unsigned int i,j;
	for (i=0; i<x;i++){
		for(j=0;j<255;j++);
	}
}


void clock_init(){
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
}



int main()
{
	clock_init();
	LCD_init();
	unsigned char key_pressed;
	LCD_WriteString("Congrats Fady !!!!");
	wait(500);
	LCD_Clear_Screen();
	SevenSeg_init();

	for (unsigned char i = 0; i < 11; i++) {
		LCD_WriteChar(P_LCD_DISPLAY[i]);
		MCAL_GPIO_WritePort(GPIOB, P_DISPLAY[i] << 9); /* write data on to the LED port */
		wait(100);
		/* wait for 1 second */
	}
	//	MCAL_GPIO_WritePort(GPIOB, 0xDE);
	//	wait_ms(100);
	LCD_Clear_Screen();
	KEYPAD_INIT();
	LCD_WriteString("Keypad is ready");
	wait(30);
	LCD_Clear_Screen();
	while(1){

		key_pressed = KEYPAD_GetChar();
		switch (key_pressed) {
		case 'A':
		break;
		case '!':
			LCD_Clear_Screen();
			break;
		default:
			LCD_WriteChar(key_pressed);
			break;
		}

	}
	return 0;}
